// This file is generated by FlutterFire CLI.
// Run: flutterfire configure
// See: https://firebase.flutter.dev/docs/cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web not supported');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoChtGi-uEV3ZWV31-yikolOfPF8pOiX4',
    appId: '1:815269999993:android:539ce470735526187b2ba8',
    messagingSenderId: '815269999993',
    projectId: 'whoisthere-380fa',
    storageBucket: 'whoisthere-380fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoChtGi-uEV3ZWV31-yikolOfPF8pOiX4',
    appId: '1:815269999993:ios:whoisthere',
    messagingSenderId: '815269999993',
    projectId: 'whoisthere-380fa',
    storageBucket: 'whoisthere-380fa.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.whoisthere.app',
  );
}
